package templates

// EchoServiceTmpl : is tmpl to create app
var EchoServiceTmpl = `// Code generated by Mestri; DO NOT EDIT.
// This file was generated by Mestri robots at
// {{ .Timestamp }}
package services

import (
	"fmt"
	"github.com/labstack/echo/v4"
    
    "time"
    "log"
    "database/sql"
    _ "github.com/lib/pq"
    {{range $i, $entity := .Entities}}
		"github.com/heraju/mestri/app/services/{{$entity}}"
	{{end}}
)


// Connect : Connect ECHO to Mestri
func Connect(e *echo.Echo, db *sql.DB) {
    timeoutContext := time.Duration(3000) * time.Second
	fmt.Println("Connecting To MESTRI!!!")
    {{range $i, $model := .Models}}
        {{$model.Package}}Repo := {{$model.Package}}.NewPgRepository(db)
        {{$model.Package}}Uc := {{$model.Package}}.NewUsecase({{$model.Package}}Repo, timeoutContext)
		{{$model.Package}}.New{{$model.ModelName}}Handler(e, {{$model.Package}}Uc)
	{{end}}
}


// Utility functions
func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}`
